import {test} from 'node:test';
import assert from 'node:assert/strict';
import {inspectWallet} from '../docs/market-preview/wallet-check.mjs';
function provider(){const calls=[];return {calls,CWI:{getVersion:async()=>{calls.push('getVersion');return {version:'2.0.0-test'};},getNetwork:async()=>{calls.push('getNetwork');return {network:'mainnet'};},isAuthenticated:async()=>{calls.push('isAuthenticated');return {authenticated:false};},createAction:()=>{throw Error('MUST NOT CALL');},signAction:()=>{throw Error('MUST NOT CALL');},abortAction:()=>{throw Error('MUST NOT CALL');},waitForAuthentication:()=>{throw Error('MUST NOT CALL');},getPublicKey:()=>{throw Error('MUST NOT CALL');}}};}
test('no read without explicit approval',async()=>{const p=provider();await assert.rejects(()=>inspectWallet(p),/USER_GESTURE_REQUIRED/);assert.deepEqual(p.calls,[]);});
test('absent provider reports unavailable not false support',async()=>{const r=await inspectWallet({},{approved:true});assert.equal(r.status,'unavailable');assert.equal(r.paidTradingEnabled,false);});
test('only three read-only calls in sequence; no authentication/key/signature/payment',async()=>{const p=provider(),r=await inspectWallet(p,{approved:true});assert.equal(r.status,'read-only-check-passed');assert.deepEqual(p.calls,['getVersion','getNetwork','isAuthenticated']);assert.equal(r.checks.isAuthenticated.authenticated,false);for(const k of ['signingTested','broadcastTested','transactionOrderingTested','providerBrandVerified'])assert.equal(r[k],false);});
test('refusal is sanitized with no raw exception',async()=>{const p=provider();p.CWI.getNetwork=async()=>{throw Error('sensitive arbitrary upstream message');};const r=await inspectWallet(p,{approved:true});assert.equal(r.status,'incomplete');assert.equal(r.checks.getNetwork.status,'refused-or-failed');assert.ok(!JSON.stringify(r).includes('sensitive'));});
test('provider property failure is controlled',async()=>{const p={get CWI(){throw Error('denied');}};assert.equal((await inspectWallet(p,{approved:true})).status,'provider-access-failed');});
test('missing methods never become success',async()=>{const r=await inspectWallet({CWI:{}},{approved:true});assert.equal(r.status,'incomplete');assert.equal(r.checks.getNetwork.status,'missing');});
test('timeout ends serial reads, no automatic retry',async()=>{const p=provider();p.CWI.getVersion=()=>new Promise(()=>{});const r=await inspectWallet(p,{approved:true,timeoutMs:5});assert.equal(r.checks.getVersion.status,'timeout');assert.deepEqual(p.calls,[]);});
for(const [name,value] of [['getNetwork',{network:'unknown'}],['getVersion',{version:'x'.repeat(65)}],['getVersion',{version:'bad\nversion'}],['isAuthenticated',{authenticated:'yes'}]])test('invalid '+name+' result is rejected '+JSON.stringify(value),async()=>{const p=provider();p.CWI[name]=async()=>value;const r=await inspectWallet(p,{approved:true});assert.equal(r.status,'incomplete');assert.equal(r.checks[name].status,'invalid-result');});
test('testnet is reported rather than relabeled mainnet',async()=>{const p=provider();p.CWI.getNetwork=async()=>({network:'testnet'});assert.equal((await inspectWallet(p,{approved:true})).checks.getNetwork.network,'testnet');});
test('invalid timeout fails before wallet call',async()=>{const p=provider();await assert.rejects(()=>inspectWallet(p,{approved:true,timeoutMs:0}),/INVALID_TIMEOUT/);assert.deepEqual(p.calls,[]);});
