import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Transaction,Script} from '@bsv/sdk';
import {WocClient,verifyCertificate,DEMO_ORIGIN,canonical,sha,mapSat,listingEvidence,ISSUERS,verifyPremintAnchor,traceOrigin} from '../src/live-evidence.mjs';
const receipt=JSON.parse(readFileSync(new URL('../../docs/nft/genesis/genesis-052-receipt.json',import.meta.url)));
const saved=JSON.parse(readFileSync(new URL('../evidence/genesis-052-api.json',import.meta.url)));
const raw=saved.transactions[0].raw,id=receipt.txid,address=saved.current.controllingAddress,scriptHash=saved.current.status.scriptHash;
const respond=(data,status=200)=>({status,ok:status===200,text:async()=>typeof data==='string'?data:JSON.stringify(data)});
const row={tx_hash:id,tx_pos:0,value:1,height:969927,status:'confirmed',isSpentInMempoolTx:false};
const index=(result=[row],extra={})=>({address,script:scriptHash,result,error:'',...extra});
const metadata={...saved.transactions[0]};delete metadata.raw;
function client(overrides={},options={}){return new WocClient({sleep:async()=>{},fetcher:async url=>{const path=url.split('/main')[1];if(path in overrides)return typeof overrides[path]==='function'?overrides[path]():overrides[path];if(path===`/tx/${id}/hex`)return respond(raw);if(path===`/tx/hash/${id}`)return respond(metadata);if(path.endsWith('/spent'))return respond('Not Found',404);if(path.endsWith('/unspent/all'))return respond(index());throw Error('UNEXPECTED_ENDPOINT');},...options});}
test('real final certificate signature, registry, raw anchor and zero-mint circularity',()=>{
 const r=verifyCertificate(receipt,DEMO_ORIGIN,raw);assert.equal(r.verified,true);assert.equal(r.demoIssuer,true);
 const mint=readFileSync(new URL('../../docs/js/mint.js',import.meta.url),'utf8');assert.ok(mint.includes(ISSUERS.GEN1.publicKey));
 assert.equal(r.commitment,sha(Buffer.from(canonical({...receipt.cert,mint:'0'.repeat(64)}))).toString('hex'));
 assert.notEqual(r.commitment,sha(Buffer.from(canonical(receipt.cert))).toString('hex'));
 assert.ok(raw.includes('006a23535632'+r.commitment));
});
for(const [name,change] of Object.entries({signature:r=>{r.envelope=r.envelope.slice(0,42)+'00'+r.envelope.slice(44);},issuer:r=>{r.envelope=r.envelope.replace('47454e31','47454e32');},canonical:r=>{r.envelope=r.envelope.replace('7b22617274','7b20227274');},zeroMint:r=>{r.cert.mint='0'.repeat(64);},wrongOrigin:r=>{r.txid='a'.repeat(64);},certificate:r=>{r.cert.art='0'.repeat(16);},schema:r=>{r.cert.extra='x';}}))test('reject '+name,()=>{const r=structuredClone(receipt);change(r);assert.throws(()=>verifyCertificate(r,DEMO_ORIGIN,raw));});
test('wrong output origin and changed raw fail',()=>{assert.throws(()=>verifyCertificate(receipt,id+':1',raw));assert.throws(()=>verifyCertificate(receipt,DEMO_ORIGIN,raw.slice(0,-2)+'01'));});
test('live shape: exact raw hash, confirmed metadata, indexed mempool false',async()=>{const c=client();assert.equal((await c.transaction(id)).raw,raw);const s=await c.status(DEMO_ORIGIN);assert.equal(s.confirmed,'unspent');assert.equal(s.mempool,'unspent');});
test('rawhash mismatch fails before metadata',async()=>{await assert.rejects(client({[`/tx/${id}/hex`]:respond(raw.slice(0,-2)+'01')}).transaction(id),/RAW_HASH/);});
for(const [name,data] of Object.entries({missing:null,unconfirmed:{...metadata,confirmations:0},wrong:{...metadata,txid:'a'.repeat(64)},block:{...metadata,blockhash:''}}))test('confirmation '+name,async()=>{await assert.rejects(client({[`/tx/hash/${id}`]:respond(data)}).transaction(id),/CONFIRMATION/);});
for(const [name,data] of Object.entries({absent:index([]),mempoolMissing:index([{...row,isSpentInMempoolTx:undefined}]),wrongValue:index([{...row,value:2}]),indexerError:index([row],{error:'lag'}),wrongScript:index([row],{script:'bad'}),duplicate:index([row,row]),pageInjection:index([row],{'next-page':'https://evil.test/a'}),pageCycle:index([row],{'next-page':`/address/${address}/unspent/all?page=1`})}))test('failclosed status '+name,async()=>{const c=client({[`/address/${address}/unspent/all`]:respond(data),[`/address/${address}/unspent/all?page=1`]:respond(index([],{'next-page':`/address/${address}/unspent/all?page=1`}))});assert.equal((await c.status(DEMO_ORIGIN)).confirmed,'unknown');});
test('404 is not unspent and 400 is unknown',async()=>{const s=await client({[`/tx/${id}/0/spent`]:respond('',400)}).status(DEMO_ORIGIN);assert.equal(s.confirmed,'unknown');});
test('spent and mempool spent are distinguished',async()=>{const spend=tx([[id,0]],[1]),sid=spend.id('hex');assert.equal((await client({[`/tx/${id}/0/spent`]:respond({txid:sid}),[`/tx/${sid}/hex`]:respond(spend.toHex()),[`/tx/hash/${sid}`]:respond({...metadata,txid:sid})}).status(DEMO_ORIGIN)).confirmed,'spent');assert.equal((await client({[`/address/${address}/unspent/all`]:respond(index([{...row,isSpentInMempoolTx:true}]))}).status(DEMO_ORIGIN)).mempool,'spent');});
test('full pagination required even after finding target',async()=>{const c=client({[`/address/${address}/unspent/all`]:respond(index([row],{'next-page':`/address/${address}/unspent/all?page=1`})),[`/address/${address}/unspent/all?page=1`]:respond(index([]))});assert.equal((await c.status(DEMO_ORIGIN)).mempool,'unspent');});
test('429 and 503 retries bounded; serialized concurrent calls',async()=>{let n=0,active=0,peak=0;const c=new WocClient({sleep:async()=>{},fetcher:async()=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,1));active--;return respond('ok',++n<=2?503:200);}});await Promise.all([c.request(`/tx/${id}/hex`),c.request(`/tx/${id}/hex`)]);assert.equal(peak,1);assert.equal(n,4);let calls=0;const bad=new WocClient({sleep:async()=>{},fetcher:async()=>{calls++;return respond('',429);}});await assert.rejects(bad.request(`/tx/${id}/hex`),/API_HTTP_429/);assert.equal(calls,3);});
test('timeout unavailable, stale view unknown, endpoint and request budgets',async()=>{const c=client({}, {timeout:5,fetcher:async(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('abort'))))});assert.equal((await c.status(DEMO_ORIGIN)).availability,'unavailable');let time=0;const stale=client({[`/address/${address}/unspent/all`]:()=>{time=16000;return respond(index());}},{clock:()=>time});assert.equal((await stale.status(DEMO_ORIGIN)).reason,'STATUS_STALE');assert.throws(()=>client().request('/broadcast'),/ENDPOINT/);await assert.rejects(client({}, {maxRequests:1}).transaction(id),/REQUEST_BUDGET/);});
test('anchor rejects final-cert circular hash, trailing script and nonzero value',()=>{for(const mode of ['final','trailing','value']){const t=Transaction.fromHex(raw);if(mode==='final')t.outputs[1].lockingScript=Script.fromHex('006a23535632'+sha(Buffer.from(canonical(receipt.cert))).toString('hex'));if(mode==='trailing')t.outputs[1].lockingScript=Script.fromHex(t.outputs[1].lockingScript.toHex()+'00');if(mode==='value')t.outputs[1].satoshis=1;assert.throws(()=>verifyPremintAnchor(receipt.cert,t),/PREMINT_ANCHOR/);}});
test('end-to-end trace follows confirmed raw spender and stops at fresh indexed output',async()=>{const spend=tx([[id,0]],[1]);spend.outputs[0].lockingScript=Transaction.fromHex(raw).outputs[0].lockingScript;const sid=spend.id('hex'),parent=saved.transactions[1];const c=client({[`/tx/${parent.txid}/hex`]:respond(parent.raw),[`/tx/hash/${parent.txid}`]:respond(parent),[`/tx/${id}/0/spent`]:respond({txid:sid}),[`/tx/${sid}/hex`]:respond(spend.toHex()),[`/tx/hash/${sid}`]:respond({...metadata,txid:sid}),[`/address/${address}/unspent/all`]:respond(index([{...row,tx_hash:sid}]))});const report=await traceOrigin(c,receipt);assert.equal(report.hops.length,1);assert.equal(report.current.outpoint,sid+':0');assert.equal(report.current.availabilityProven,true);assert.equal(report.current.keyPossessionProven,false);});
test('spender not consuming exact prevout, missing spender and hop budget fail closed',async()=>{const spend=tx([[id,1]],[1]),sid=spend.id('hex');const c=client({[`/tx/${id}/0/spent`]:respond({txid:sid}),[`/tx/${sid}/hex`]:respond(spend.toHex()),[`/tx/hash/${sid}`]:respond({...metadata,txid:sid})});assert.equal((await c.status(DEMO_ORIGIN)).reason,'SPENDER_LINEAGE');assert.equal((await client({[`/tx/${id}/0/spent`]:respond({txid:'a'.repeat(64)})}).status(DEMO_ORIGIN)).confirmed,'unknown');const fake={transaction:async tid=>({tx:Transaction.fromHex(saved.transactions.find(t=>t.txid===tid)?.raw??raw),raw}),status:async()=>({spender:sid}),clock:Date.now};await assert.rejects(traceOrigin(fake,receipt,DEMO_ORIGIN,{maxHops:0}),/HOP_BUDGET/);});
function tx(inputs,values){return new Transaction(1,inputs.map(([sourceTXID,sourceOutputIndex])=>({sourceTXID,sourceOutputIndex,unlockingScript:Script.fromHex('51'),sequence:0xffffffff})),values.map(satoshis=>({satoshis,lockingScript:Script.fromHex('51')})),0);}
test('sat-flow resolves all parents and maps nonzero input/output indices with BigInt',async()=>{const front=tx([['a'.repeat(64),0]],[5000]),asset=tx([['b'.repeat(64),0]],[1]),last=tx([['c'.repeat(64),0]],[50]);const spend=tx([[front.id('hex'),0],[asset.id('hex'),0],[last.id('hex'),0]],[4000,1000,1,40]);const all=new Map([front,asset,last,spend].map(t=>[t.id('hex'),{tx:t}])),reads=[];const c={transaction:async id=>{reads.push(id);if(!all.has(id))throw Error('PARENT_UNKNOWN');return all.get(id);}};const mapped=await mapSat(c,spend.id('hex'),asset.id('hex')+':0');assert.equal(mapped.outpoint,spend.id('hex')+':2');assert.equal(mapped.absoluteOffset,'5000');assert.equal(reads.length,4);const wrong=tx(spend.inputs.map(i=>[i.sourceTXID,i.sourceOutputIndex]),[5001,1,39]);all.set(wrong.id('hex'),{tx:wrong});const actual=await mapSat(c,wrong.id('hex'),asset.id('hex')+':0');assert.equal(actual.outpoint,wrong.id('hex')+':0');assert.equal(actual.offset,'5000');all.delete(last.id('hex'));await assert.rejects(mapSat(c,spend.id('hex'),asset.id('hex')+':0'),/PARENT_UNKNOWN/);});
test('funding requires explicit trusted provenance; demo never satisfies paid origin gate',async()=>{const c=client(),e=listingEvidence(c,receipt);assert.equal(await e.verifyFunding({outpoint:DEMO_ORIGIN,raw}),false);assert.equal(await e.verifyOrigin({origin:DEMO_ORIGIN,raw}),false);assert.equal(await e.verifyTransaction({txid:id,raw}),true);const partial=listingEvidence(c,receipt,{approvedFunding:[{outpoint:DEMO_ORIGIN,raw,walletApproved:true,assetFree:true}]});assert.equal(await partial.verifyFunding({outpoint:DEMO_ORIGIN,raw}),false);});
